### ISSUE TITLE
Tool will get stuck when loading some resources

### ISSUE THREAD

**Issue by gazer099** [fcu-d0441320/iLearnBackupTool#2]
![Imgur](https://i.imgur.com/yG2Gdd6.png)
![Imgur](https://i.imgur.com/m4PTKMe.png)
![Imgur](https://i.imgur.com/22toHJf.png)
When I load the course [{'title': '資訊工程學系訊息公告社群', 'id': '=8984'}]
The tool can not load it, and I can't do anything until I finish loading all the courses.

**Comment by dream-rhythm** [comment]
I try to fix this bug in v1.2, you can try it.
This problem is cause by can not find main div, and list index out of range not handle.
